import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Order Summary Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <div className={styles.wrapper}>
        <img
          className={styles.hero}
          src="/illustration-hero.svg"
          alt="Illustration"
        />
        <h3 className={styles.title}>Order Summary</h3>
        <p className={styles.desc}>
          You can now listen to millions of songs, audiobooks, and podcasts of
          any device anywhere you like!
        </p>
        <div className={styles.plan}>
          <img src="/icon-music.svg" alt="Music Icon" />
          <div className={styles.planWrapper}>
            <h3>Annual Plan</h3>
            <p>$59.99/year</p>
          </div>
          <p className={styles.change}>Change</p>
        </div>
        <div className={styles.buttonWrapper}>
          <button className={styles.buttonPrimary}>Proceed to Payment</button>
          <button className={styles.buttonSecondary}>Cancel Order</button>
        </div>
      </div>
    </div>
  );
}
